level_four/urls.py
from django.urls import path
from level_four import views

# Need to register application name in a variable
# for Django to find the relative URLs paths
app_name = "app_four_application"

urlpatterns = [
    # using different methods to connect with views.func()
    path('', views.app_four, name="app_four_main"),
    path('relative-path', views.relative_url_template, name="relative")
]

level_one/urls.py
from django.urls import path
from level_one import views

urlpatterns = [
    path('app_prefix/', views.index, name='index')
]

test_project01/urls.py
from django.contrib import admin
from django.urls import path
# from level_one import views as app1_views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', app1_views.index, name="main-view")
    # Use 'include' to import all the URLs in the Django App
    path("project_prefix/", include('level_one.urls')),
    path("level_two/", include('level_two.urls')),
    path("level_three/", include('level_three.urls')),
    path("level_four/", include('level_four.urls')),
    path('level_five/', include('level_five.urls'))

]

level_four/views.py
from django.shortcuts import render

# Create your views here.
def app_four(request):
    return render(request, "app_four.html")


def relative_url_template(request):
    return render(request, "relative_html_page.html")

level_four/templates/app_four.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Relative Template Tagging</title>
</head>
<body>

{% block body_block %}

<p>Hi Moosa !</p>
<!--    We use relative URLs as below : -->
<p>Click <a href="{% url 'app_four_application:relative' %}" >here</a> to get redirected to another page uring Relative Path URL.</p>

<h3> What is Lorem Ipsum? </h3>
<p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>

{% endblock %}
</body>
</html>

level_four/templates/relative_html_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>relative Html Page</title>
</head>
<body>
    <p>Hello, This is the HTML Page redirected from relative URL from the main page.</p>

</body>
</html>