level_five/urls.py
from django.urls import path
from level_five import views

# Relative URL Paths
app_name = "level_five_app"

urlpatterns =[
    path('', views.level_index, name='level_index'),
    path('register/', views.register, name='registration'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('special/', views.special, name='special'),
]

level_one/urls.py
from django.urls import path
from level_one import views

urlpatterns = [
    path('app_prefix/', views.index, name='index')
]

test_project01/urls.py
from django.contrib import admin
from django.urls import path
# from level_one import views as app1_views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', app1_views.index, name="main-view")
    # Use 'include' to import all the URLs in the Django App
    path("project_prefix/", include('level_one.urls')),
    path("level_two/", include('level_two.urls')),
    path("level_three/", include('level_three.urls')),
    path("level_four/", include('level_four.urls')),
    path('level_five/', include('level_five.urls'))

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forms</title>
    <!--    Bootstrap Link   -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- Bootstrap JS Link to be added below the body tag -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>
</head>
<body>

<!--    Standard Navbar Bootstrap Code   -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav">
        <li class="navbar-brand">
            <a class="nav-link" href="{% url 'level_five_app:level_index' %}">Home</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="http://127.0.0.1:8000/admin/">Admin</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'level_five_app:registration' %}">Register</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'level_five_app:logout' %}">Logout</a></li>
        {% else %}
            <li class="nav-item active"><a class="nav-link" href="{% url 'level_five_app:login' %}">Login</a></li>
        {% endif %}
    </ul>
</nav>

<nav class="navbar navbar-default">
    <div class="container">
        <ul class="nav navbar-nav">

        </ul>

    </div>
</nav>
<div class="mt-4 p-5 bg-secondary-subtle text-black rounded">
    <div class="contrainer">

    {% block body_block %}
    {% endblock %}

    </div>
</div>

</body>
</html>